app = "taskmaster-mcp"
primary_region = "mia"

[env]
  LOG_LEVEL = "debug"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
