app = "taskmaster-mcp"
primary_region = "mia"

[env]
  LOG_LEVEL = "debug"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[processes]
  app = "python task_master_server.py"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
