app = "taskmaster-mcp"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL = "debug"
  PORT = "8000"

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 8000
  min_machines_running = 1
  processes = [ "app" ]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
