# fly.toml app configuration file generated for taskmaster-mcp on 2025-04-26T04:53:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taskmaster-mcp'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
